### PR TITLE
WIP: spilu gmres for steady Navier-Stokes Newton iteration

### PR DESCRIPTION
**Pull request by gdmcbain**
This fixes #169 and is based on the branch `gdmcbain:ns` in #145 rather than `master`.

This works, achieving (graphically) similar results to the direct Newton solver for steady Navier&ndash;Stokes in #145, but avoiding all calls to `skfem.utils.solve`, replacing them with:
* `splu` factorization of the (condensed) Stokes matrix, with backsolves for the initial guess for
  * natural parameter continuation (`pacopy.natural`)
  * GMRES inside `jacobian_solver`
* GMRES for Newton Navier&ndash;Stokes with `spilu` preconditioner

as suggested in https://github.com/kinnala/scikit-fem/pull/162#issuecomment-480499778 and taken up in #169.

It works, but little attempt has been made as yet to tune the parameters (`spilu`, `gmres`, `pacopy.natural`) or see to what extent it improves scalability for finer meshes.

### CODE REVIEW

**Comment by gdmcbain** [comment]
Thus far `skfem.utils.solve` is avoided; there is no attempt to use its `solver` keyword-argument.

**Comment by gdmcbain** [comment]
Oops, I didn't notice `skfem.utils.build_pc_ilu`, as used in `ex09`.

**Comment by gdmcbain** [comment]
Preliminary findings here are that though this is easy to implement, it doesn't help.  On coarse grids, it's slightly slower than the direct solver; on finer grids, it diverges.  This could be merely a matter of tuning the various parameters, but perhaps a scheme more designed for saddle-point problems is required; see, e.g. Braess (2001, §IV.5 ‘Saddle point problems’).

**Comment by kinnala** [comment]
In any case, going iterative is probably not worth the additional work required? I've always gotten the impression that iterative methods require too much work on preconditioners, parameters, initial guesses, etc. to be worth the trouble unless you really need to distribute to huge number of computational nodes: implementing iterative methods for clusters is much easier than direct methods.

**Comment by gdmcbain** [comment]
Hmm, not sure.  My experience on fairly basic multiprocessor (multi = 4, 8, or 16) single hosts is that direct solvers run out of memory for larger problems which includes all but the smallest three-dimensional ones and that even for basic Laplace or Poisson problems like ex13 it's necessary to resort to some kind of preconditioned conjugate gradient (as in ex09).  This happens at a much smaller size for mixed finite element problems like Stokes which require some kind of Uzawa conjugate gradient iteration.

*  Glowinski, R. & Pironneau, O. (1979). On numerical methods for the Stokes problem. In R. Glowinski, E. Y. Rodin & O. C. Zienkiewicz (eds.), _Energy Methods in Finite Element Analysis_ (pp. 243–264), Chichester: John Wiley & Sons

I think this is related to today's 'block preconditioners' and called 'fieldsplit' in PETSc.  It continues to be an active research area; see, e.g.

*  Elman, H. C., Silvester, D. J., & Wathen, A. J. (2014) [_Finite Elements and Fast Iterative Solvers : with Applications in Incompressible Fluid Dynamics_](http://dx.doi.org/10.1093/acprof:oso/9780199678792.001.0001). Oxford University Press

I'll close this for the moment, along with the time-consuming example kinnala/scikit-fem#162 that prompted it, but I do hope to return to preconditioned iteration later.  I think scikit-fem should be great for testing different approaches; ex09 and the code here are clear and easy.

**Pull request closed without merging**
